---
- name: lidarr - pull and configure
  docker_container:
    name: lidarr
    image: linuxserver/lidarr
    pull: true
    network_mode: container:openvpn-client
    env:
      PGID: "65534"
      PUID: "65534"
    volumes:
      - /opt/config/lidarr:/config:rw
      - /data/shares/Media/Music:/music:rw
      - /data/shares/Downloads:/downloads:rw
    restart_policy: always
