---
- name: plexcleaner - pull and configure
  docker_container:
    name: plexcleaner
    image: ptr727/plexcleaner
    pull: true
    env:
      TZ: "America/New_York"
    user: nobody:nogroup
    devices:
      - /dev/dri/card1:/dev/dri/card1:rwm
      - /dev/dri/renderD128:/dev/dri/renderD128:rwm
    volumes:
      - /opt/config/plexcleaner:/config:rw
      - /data/shares/Media:/media:rw
    restart_policy: always
    command:
      - /PlexCleaner/PlexCleaner
      - monitor
      - --logfile=/config/PlexCleaner.log
      - --settingsfile=/config/PlexCleaner.json
      - --mediafiles=/media/Anime
      - --mediafiles=/media/Children
      - --mediafiles=/media/Movies
