---
- name: qbittorrent - pull and configure
  docker_container:
    name: qbittorrent
    image: linuxserver/qbittorrent
    pull: true
    network_mode: container:openvpn-client
    env:
      PGID: "65534"
      PUID: "65534"
    volumes:
      - /opt/config/qbittorrent:/config:rw
      - /data/shares/Downloads:/downloads:rw
    restart_policy: always
